### ISSUE TITLE
Ajouter des fichiers séparés pour chaque fonction

### ISSUE THREAD

**Issue by BooLooBooLoo** [Zalk0/GL02_Les_Sealanders#5]
## Contexte : 

Pour les développeurs, le fichier CaporalCli.js contient 617 lignes. Toutes les fonctions utilisées sont détaillés dans ce fichier.

## Description :

Un nouveau dossier nommé "fonctions" doit être créer et contiendra un fichier javascript par fonctions présentes dans le fichier CaporalCli.js. On déplacera le code de chaque fonction dans son fichier et on appliquera les changements nécessaires au fonctionnement dans CaporalCli.js. Rajouter des commentaires pour chaque fonction sera nécessaire pour faciliter la compréhension.

## Motivation : 

Relire le code dans son état actuel est fastidieux. Séparer les différentes parties du code permettra de faciliter la lisibilité et de trouver plus facilement les parties du code qui nous intéressent. Les commentaires que nous allons ajoutés auront aussi cette fonction de facilitation de la compréhension.

**Comment by Zalk0** [comment]
Fait dans la PR #13
